console.log("#1");
var sweety = "sweety";
var cutie ="cutie";
console.log("_____Before Swap_____");
console.log(sweety,cutie);
var temp = sweety;
var sweety = cutie;
var cutie = temp;
console.log("_____After Swap");
console.log(sweety,cutie);
console.log("________________________________________________________________________________");
console.log("#2");
var num1 = 100;
var num2 = 200;
var num3 = 300;
console.log("_____Before Swap_____");
console.log(num1,num2,num3);
var temp = num1;
num1 = num2;
num2 = num3;
num3 = temp;
console.log("_____After Swap_____");
console.log(num1,num2,num3);